.catalog:
  name: "Kibana"
  version: "4.1.1-rancher1"
  description: "Kibana: Explore & Visualize Your Data"
  uuid: kibana-0
  questions:
    - variable: "elasticsearch_source"
      description: "Link to elasticsearch service or stack/service"
      label: "Elasticsearch source"
      type: "service"
      required: true
      default: "es/elasticsearch-clients"
nginx-proxy:
  metadata:
    nginx:
      conf:
        servername: "kibana"
	username: "admin"
	password: "{SHA}bovSm2f6yv6Xe3Pinz0gfTy+PnA="
        upstream_port: 5601 
